# Generated by Django 5.1.3 on 2024-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='third_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
